// Static page content and generation. No client router or build dependency.
import {readFileSync,writeFileSync} from 'node:fs';
import {pathways} from '../public/pathways.js';
const root = new URL('../public/', import.meta.url);
const read = name => readFileSync(new URL(name,root),'utf8');
const write = (name,text) => writeFileSync(new URL(name,root),text);
const esc = s => s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const cards = (title,items) => `<section class="guide-section"><h2>${title}</h2><div class="guide-grid">${items.map(([h,p],i)=>`<article class="guide-card"><span class="eyebrow">0${i+1}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section>`;
const steps = (title,items) => `<section class="guide-section"><h2>${title}</h2><ol class="guide-steps">${items.map(([h,p])=>`<li><h3>${h}</h3><p>${p}</p></li>`).join('')}</ol></section>`;
const check = (title,items) => `<section class="guide-section guide-check"><h2>${title}</h2><p>Use this checklist as you work. Checks stay on this page until you reload.</p>${items.map(t=>`<label><input type="checkbox"> <span>${t}</span></label>`).join('')}</section>`;
const links = (items) => `<section class="guide-section"><h2>Keep exploring.</h2><div class="guide-links">${items.map(([t,url,p])=>`<a href="${url}"><h3>${t} <span aria-hidden="true">+</span></h3><p>${p}</p></a>`).join('')}</div></section>`;
const note = (title,text) => `<aside class="guide-note"><h2>${title}</h2><p>${text}</p></aside>`;
export const pages = [
{slug:'college-admissions-advising',title:'College & Admissions Advising',group:'Product',tag:'A plan that starts with you.',intro:'Make your college search more manageable with guidance on your priorities, your options and your next step. Bring your questions; you do not need a finished plan.',image:21,body:
cards('What we can work through together.',[['Your priorities','Talk through what you want from college: subjects, support, community, location and the cost your family can manage.'],['Your college list','Compare academic and financial fit across a range of options. A balanced list includes colleges you would be glad to attend, not just names you recognize.'],['Your application plan','Break requirements into milestones, identify questions for your counselor and make space for drafts, recommendations and final reviews.']])+
steps('Build a balanced list.',[['Begin with non-negotiables','Write down your must-haves and practical limits. Separate them from preferences you could trade off.'],['Research beyond the headline','Look at course catalogs, student support and graduation outcomes. Use each college’s net price calculator to explore affordability.'],['Keep options open','Consider a range of admissions selectivity, including realistic and affordable options. No admission or aid outcome is guaranteed.'],['Review your list again','As you learn more, remove colleges that no longer fit and record why the remaining ones matter to you.']])+
check('Bring to a first conversation.', ['Your current grade or applicant type','A few interests or questions','Any colleges you are considering','Your closest deadlines','Affordability or support needs you want to discuss'])+links([['College Planning','college-planning.html','Turn your goals into manageable milestones.'],['Request guidance','join.html','Tell us what you would like help with.']])},
{slug:'college-exploration',title:'College Exploration',group:'Product',tag:'Find your kind of place.',intro:'A college is more than its ranking. Explore how you want to learn, where you want to live and what helps you feel supported.',image:24,body:
cards('Look through three lenses.',[['Academic life','Compare majors, sample courses, class sizes and flexibility to change direction. Ask how students access research, advising or hands-on learning.'],['Daily life','Consider campus size, location, housing, transport and communities you might join. Imagine an ordinary weekday, not just a campus tour.'],['Practical fit','Compare estimated net costs, travel expenses, accessibility and available support. Check whether important resources have eligibility requirements.']])+
`<section class="guide-section"><h2>Ask better questions on a visit.</h2><dl class="guide-prompts"><dt>In the classroom</dt><dd>What happens when a student struggles in an introductory course? How easy is it to meet an instructor?</dd><dt>Outside the classroom</dt><dd>Where do students spend time between classes? What is campus like on weekends?</dd><dt>Before applying</dt><dd>Can I study my intended subject here? What is the estimated cost for my situation, and how might it change?</dd></dl></section>`+
note('Try a two-college comparison.','Choose two colleges that interest you. For each, record one course you would take, one support resource you might use, an estimated net cost and one unanswered question. Notice what matters most when you compare them.')+links([['College Scorecard','https://collegescorecard.ed.gov/','Explore U.S. Department of Education college data.'],['College Planning','college-planning.html','Use what you learn to shape your list.']])},
{slug:'application-guidance',title:'Application Guidance',group:'Product',tag:'One step at a time.',intro:'Applications feel more manageable when each requirement has a place. Start with your college’s official instructions, then build a checklist around your applicant type and entry term.',image:28,body:
steps('From requirements to submission.',[['Choose the right application','Check the college’s admissions website for accepted platforms and first-year or transfer instructions. A shared platform does not mean shared deadlines.'],['Gather your materials','Organize coursework, activities and responsibilities. Ask your school how to request transcripts and recommendations; allow time for other people’s work.'],['Plan the writing','List each required essay, supplement or portfolio. Keep prompts with your drafts so you can check that every response answers the question.'],['Review and follow through','Preview each submission, confirm any fee or waiver steps and save the confirmation. Check the college portal afterward for missing documents.']])+
check('Before you press submit.', ['Correct college, term and applicant type','Names and contact information checked','Required sections completed accurately','Writing proofread in the application preview','Recommenders and school documents requested','Deadline and time zone confirmed on the official site','Submission receipt and follow-up portal saved'])+
links([['Application Pathways','application-pathways.html','Compare the six platforms featured on our site.'],['Common App first-year guide','https://www.commonapp.org/apply/first-year-students/','Official guidance on materials, requirements and submission.']])},
{slug:'essay-storytelling-support',title:'Essay & Storytelling Support',group:'Product',tag:'Your story. Your voice.',intro:'You do not need a dramatic life event to write meaningfully. Begin with a specific moment, what you did and what it shows about how you think.',image:27,body:
cards('Support at each stage.',[['Find a starting point','Collect moments from school, work, family responsibilities, hobbies or your community. Notice where you made a choice, solved a problem or changed your mind.'],['Shape a draft','Choose one idea to explore. Use concrete details, then make room to explain why the experience matters to you now.'],['Revise with purpose','Ask whether the draft answers the prompt, sounds like you and adds something useful to the application. Revise structure before polishing individual sentences.']])+
note('Student-led, always.','We can help you brainstorm, organize ideas and consider feedback. Your application writing must remain your own work. Do not invent experiences or ask someone else to write your submission. Follow each application’s authorship and AI-use rules.')+
steps('A useful feedback conversation.',[['Tell your reader what you need','Ask about one concern: clarity, structure or whether your main idea comes through.'],['Listen for patterns','If readers are confused in the same place, revisit that section. You do not have to accept every stylistic suggestion.'],['Read it aloud','Notice language you would never use in conversation. Keep the meaning and make the voice your own.']])+links([['Essay Resources','essay-resources.html','Try practical brainstorming and revision exercises.'],['Ask for essay support','join.html','Tell us your prompt and where you are in the process.']])},
{slug:'opportunity-scholarship-guidance',title:'Opportunity & Scholarship Guidance',group:'Product',tag:'Make room for opportunity.',intro:'Explore scholarships and learning opportunities with a plan for checking eligibility, deadlines and fit. A focused search can be more useful than a long list of links.',image:30,body:
steps('Build a search you can maintain.',[['Start close to home','Ask your school counselor about local foundations, community organizations and school-based opportunities. Check colleges’ own scholarship pages.'],['Read the requirements first','Review applicant status, location, course of study and any renewal conditions before spending time on an application.'],['Track the complete commitment','Record the official link, due date, materials and whether an award is renewable. For programs, include travel, attendance and participation costs.'],['Choose where to focus','Prioritize opportunities that fit your situation and leave time for required essays or recommendations.']])+
cards('Questions worth asking.',[['What will it cover?','Check how funds are paid and what expenses they may support. Ask the college how an outside award could affect your financial-aid offer.'],['What happens next year?','Look for renewal conditions, continuing eligibility and any separate annual application.'],['Is the source trustworthy?','Confirm the sponsor and official website. Be cautious about guaranteed awards, pressure to act or requests for payment to access aid.']])+links([['Scholarship & Financial-Aid Resources','scholarship-financial-aid-resources.html','Understand aid types and find official starting points.'],['Talk through opportunities','join.html','Bring an opportunity you are considering.']])},
{slug:'long-term-mentorship',title:'Long-Term Mentorship',group:'Product',tag:'Keep looking forward.',intro:'Your goals can change as you learn more about yourself. Mentorship offers space to reflect, plan and keep moving beyond a single application deadline.',image:26,body:
cards('A conversation that can grow with you.',[['Explore','Name your interests and uncertainties. Choose something small to try, such as researching a course or talking with someone in a field that interests you.'],['Act','Choose a next step that fits your time and circumstances. Make the task clear enough to know when you have done it.'],['Reflect','Discuss what you learned, what felt difficult and what you would change. Adjust your plan as your priorities develop.']])+
`<section class="guide-section"><h2>A simple check-in agenda.</h2><ol class="guide-steps"><li><h3>Since last time</h3><p>What did I try? What surprised me?</p></li><li><h3>Right now</h3><p>What is one obstacle I want to work through?</p></li><li><h3>Before next time</h3><p>What will I do, what support do I need and when will I revisit it?</p></li></ol></section>`+
note('Start with your situation.','Tell us what you hope to work on and what kind of guidance would help. Discuss expectations and availability with us rather than assuming a particular meeting schedule or assigned mentor.')+links([['Get involved','join.html','Share your goals and ask about support.'],['About Us','about.html','Meet the people and purpose behind the project.']])},
{slug:'application-pathways',title:'Application Pathways',group:'Resources',tag:'Different paths. Your destination.',intro:'Use this guide to understand the application platforms featured on our homepage. The college’s official admissions instructions determine which route, materials and deadlines apply to you.',image:31,body:
`<section class="guide-section"><h2>Explore the six pathways.</h2><div class="guide-grid pathway-guide">${pathways.map(p=>`<article class="guide-card"><h3>${esc(p.name)}</h3><p>${esc(p.overview.replace('more than 1,100 member colleges worldwide','participating member colleges worldwide'))}</p><h4>Who is this for?</h4><p>${esc(p.who)}</p><a class="text-link" href="${p.source}">Official application guide</a></article>`).join('')}</div></section>`+
note('Check before you choose.','Membership, fees, eligibility, deadlines and binding commitments can change. Read the official guide for the current cycle and confirm each college’s requirements. Using a platform does not guarantee admission or financial aid.')+check('For each college, confirm:', ['Accepted application platform','First-year or transfer requirements','Entry term and deadline','Required writing, transcripts and recommendations','Fees, waiver options and any binding agreement'])+links([['Application Guidance','application-guidance.html','Organize the steps from preparation through follow-up.']])},
{slug:'college-planning',title:'College Planning',group:'Resources',tag:'A little clarity goes a long way.',intro:'Build a flexible plan around your next decision. These phases are a starting point, not a fixed calendar; use official deadlines for your colleges and entry term.',image:29,body:
steps('A timeline you can adapt.',[['Explore your options','Reflect on interests, academic preparation and support needs. Research several types of colleges and talk about affordability early.'],['Build your list','Compare programs and estimated costs. Record application routes, required materials and deadlines in one place.'],['Prepare your applications','Allow time for writing and feedback. Ask recommenders early, request school documents and confirm each college’s instructions.'],['Review decisions','Compare admission conditions and complete aid offers, not just award headlines. Ask questions before making a commitment.'],['Prepare for the transition','Track enrollment tasks, housing, orientation and final documents. Locate academic and wellbeing support before you need it.']])+
check('Your planning essentials.', ['One place to track deadlines','A list of required documents','A plan for application costs or fee waivers','Estimated net costs for colleges on your list','Time to review decisions with a trusted person'])+links([['College Exploration','college-exploration.html','Look beyond rankings to academic and personal fit.'],['Financial-Aid Resources','scholarship-financial-aid-resources.html','Prepare questions about affordability.']])},
{slug:'essay-resources',title:'Essay Resources',group:'Resources',tag:'Start with a moment.',intro:'Try these exercises before choosing a topic or polishing a draft. Use the exact prompt and word limit published by the application you are completing.',image:32,body:
cards('Three ways into a first draft.',[['The small moment','Describe an ordinary moment you remember clearly. What did you notice that someone else might miss? What does that reveal about you?'],['The responsibility','Think of something people rely on you to do. Describe a choice you made while doing it and why that choice mattered.'],['The changed mind','Recall a question, conversation or experience that shifted your thinking. What did you believe before, and what do you understand differently now?']])+
steps('Revise from the inside out.',[['Name the point','Write a one-sentence note about what you want the reader to understand. Does the draft support it?'],['Look for evidence','Replace broad claims with specific actions and details. Explain what those details mean without repeating them.'],['Check the prompt','Remove material that belongs in another response. Check the required length and application instructions.'],['Keep your voice','Read aloud and simplify language that feels borrowed. Check names, dates and formatting in the submission preview.']])+links([['Common App application guide','https://www.commonapp.org/apply/first-year-students/','Check college-specific writing requirements and plan essays.'],['UC personal insight questions','https://admission.universityofcalifornia.edu/how-to-apply/applying-as-a-first-year/personal-insight-questions.html','Read the official first-year questions and writing guidance.'],['Essay & Storytelling Support','essay-storytelling-support.html','Learn how student-led feedback can help.']])},
{slug:'scholarship-financial-aid-resources',title:'Scholarship & Financial-Aid Resources',group:'Resources',tag:'Understand the cost. Explore the help.',intro:'Start with official aid information and each college’s financial-aid office. Eligibility and requirements depend on your situation, school and application year.',image:33,body:
cards('Understand an aid offer.',[['Grants and scholarships','These generally do not require repayment, but conditions can apply. Check eligibility, renewal requirements and what happens if enrollment changes.'],['Work-study','An opportunity to earn money through eligible work. An award is not the same as cash available upfront to pay a bill.'],['Loans','Borrowed money that must be repaid under the loan’s terms. Compare the amount, interest and repayment obligations before accepting.']])+
steps('Approach the FAFSA with a plan.',[['Use the official starting point','Go to StudentAid.gov for the correct FAFSA form, current instructions and eligibility information. Do not rely on a deadline from a previous year.'],['Check all deadlines','Federal, state and college deadlines may differ. Colleges may also require additional aid forms.'],['Follow the contributor instructions','Use official guidance to understand who needs to provide information. Each person should keep their own account credentials private.'],['Review and follow up','Check the processed application and respond to requests from colleges. Contact the aid office if your circumstances need explanation.']])+
note('Compare net costs, not just awards.','List tuition, housing, meals, fees, books and travel. Subtract grants and scholarships to estimate net cost; consider loans and work separately. Ask what may change in later years and whether an award renews.')+links([['Federal Student Aid','https://studentaid.gov/','Official FAFSA, eligibility and account guidance.'],['Types of aid','https://studentaid.gov/understand-aid/types','Understand grants, scholarships, work-study and loans.'],['Opportunity & Scholarship Guidance','opportunity-scholarship-guidance.html','Build a focused search and track requirements.']])},
{slug:'student-guides',title:'Student Guides',group:'Resources',tag:'Find your next useful step.',intro:'Choose a guide for the question you have now. You can begin with exploration, work on an application or return to planning whenever your goals change.',image:25,body:
links([['I am exploring','college-exploration.html','Compare academic life, campus environments and personal fit.'],['I want a plan','college-planning.html','Build a flexible timeline and a useful checklist.'],['I am choosing an application','application-pathways.html','Find official guides to the six featured pathways.'],['I am preparing to submit','application-guidance.html','Gather materials, review requirements and follow through.'],['I am working on my writing','essay-resources.html','Try brainstorming and revision exercises.'],['I am considering costs','scholarship-financial-aid-resources.html','Learn the vocabulary and find official aid resources.']])+
note('Make a guide work for you.','Choose one task from a guide, decide when you will try it and write down the question that remains afterward. Bring that question to a counselor, a trusted supporter or our team.')+links([['Ask for guidance','join.html','You do not need to navigate every step on your own.']])},
{slug:'faq',title:'Frequently Asked Questions',group:'Resources',tag:'Good questions deserve clear answers.',intro:'Learn how to start, what support can cover and what remains your decision. For specific college requirements, always check the institution’s official instructions.',image:null,body:
`<section class="guide-section"><h2>About our support.</h2><div class="faq-list"></div></section>`+links([['Contact Us','contact.html','Have another question? Prepare an email to the team.'],['Join Us','join.html','Introduce yourself and the support you are looking for.']])},
{slug:'contact',title:'Contact Us',group:'Resources',tag:'Bring your questions.',intro:'Tell us what you are exploring or where you feel stuck. A short introduction and one clear question are enough to begin.',image:null,body:
`<section class="guide-section contact-layout"><div><h2>Write to the team.</h2><p><a href="mailto:admissionpossible.official@gmail.com">admissionpossible.official@gmail.com</a></p><p>Include your question and any relevant deadline. Please do not email passwords, financial records or identification documents.</p><p>To introduce yourself for ongoing support, use the <a href="join.html">Join Us form</a>.</p></div><form id="contact-form"><label>Your name <input name="name" autocomplete="name" required maxlength="100"></label><label>Your question <textarea name="message" rows="6" required maxlength="3000"></textarea></label><button class="button dark" type="submit">Prepare email</button><p>This prepares a draft. Nothing is sent automatically; review and send it in your email app.</p><div id="contact-result" hidden><label>Prepared message<textarea id="contact-copy" rows="7" readonly></textarea></label><a class="text-link" id="contact-email">Open email app</a><p>No email app? Copy the message and send it to the address above.</p></div></form></section>`+links([['Frequently Asked Questions','faq.html','Find answers about the support we offer.'],['About Us','about.html','Learn more about the project.']])}
];
let home = read('index.html');
const menu = pages.map(p=>[p.title,p.slug+'.html']);
const updateLinks = html => html.replace(/<a\b([^>]*?)href="[^"]*"([^>]*)>([^<]+)<\/a>/g,(all,before,after,label)=>{
  const normalized=label.replaceAll('&amp;','&').trim();
  const match=menu.find(([title])=>title===normalized) || (normalized==='FAQ'?['','faq.html']:null);
  return match?`<a${before}href="${match[1]}"${after.replace(/ target="_blank"/g,'')}>${label}</a>`:all;
});
home=updateLinks(home);
if(!home.includes('cinematic-hero') && !home.includes('src="intro.js"')) home=home.replace('</head>','<link rel="stylesheet" href="intro.css"><script src="intro.js"></script></head>');
write('index.html',home);
for(const name of ['about.html','join.html']) write(name,updateLinks(read(name)));
const header=home.match(/<header[\s\S]*?<\/header>/)[0];
const footer=home.match(/<footer[\s\S]*?<\/footer>/)[0].replaceAll('href="#main"','href="#page-main"').replace(/href="#(?!page-main)([^"]+)"/g,'href="./#$1"');
for(const p of pages){
 const image=p.image===null?'':`<figure><img src="assets/campus-${p.image}.webp" alt="University campus" width="640" height="480"><figcaption>Explore a future that fits you.</figcaption></figure>`;
 write(p.slug+'.html',`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(p.title)} — (Ad)mission Possible</title><meta name="description" content="${esc(p.intro)}"><link rel="icon" href="assets/brand.webp"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="refinements.css"><link rel="stylesheet" href="guides.css"><script type="module" src="app.js"></script><script src="guides.js" defer></script></head>
<body class="guide-site"><a class="skip" href="#page-main">Skip to content</a>${header}<main id="page-main"><section class="guide-hero ${image?'':'guide-hero-text'}"><div><p class="eyebrow"><a href="./">Home</a> / ${p.group}</p><h1>${esc(p.title)}</h1><p class="guide-tag">${p.tag}</p><p>${p.intro}</p><a class="text-link" href="#guide-content">Explore this guide <span aria-hidden="true">↓</span></a></div>${image}</section><div id="guide-content" class="guide-content">${p.body}<section class="guide-cta"><p class="eyebrow">YOUR NEXT STEP</p><h2>Let’s make it <em>possible.</em></h2><p>Tell us where you are and what you would like to work on.</p><a class="button dark" href="join.html">Start for Free <span aria-hidden="true">+</span></a></section></div></main>${footer}</body></html>\n`);
}
console.log(`Generated ${pages.length} landing pages and updated navigation.`);
